### ISSUE TITLE
Connection recovery

### ISSUE THREAD

**Issue by vicneanschi** [amqp-node/amqplib#163] opened 2015-06-23 17:52 UTC
It would be nice to have a reconnect options.
Looks like there is a Java implementation for that feature https://www.rabbitmq.com/api-guide.html#recovery

**Comment by cookie-bytes** [comment] 2015-06-29 15:14
:+1:

**Comment by jamlen** [comment] 2015-06-30 14:56
:+1:

**Comment by jgato** [comment] 2015-07-16 08:40
+1

**Comment by ralcini** [comment] 2015-07-17 15:06
+1

**Comment by rikaardhosein** [comment] 2015-07-18 18:40
I'm going to have a go at implementing this.

**Comment by sreeix** [comment] 2015-07-24 11:57
+1

**Comment by squaremo** [comment] 2015-07-29 21:53
@rikaardhosein Bunny (https://github.com/ruby-amqp/bunny) and the RabbitMQ Java client (https://github.com/rabbitmq/rabbitmq-java-client) may be good examples to follow. The latter is based on the former, I believe, but maybe have innovations.

You can read my reservations and fears about auto-recovery in the issue #25. As MK points out there, the model in bunny/rabbitmq-java-client is pretty well proven by now, so perhaps my fears are unfounded.

**Comment by michaelklishin** [comment] 2015-07-29 22:22
@squaremo @rikaardhosein  the first client to implement automatic connection recovery was amqp gem. Then Bunny, then Java client and .NET. Note that Java client and Bunny have pretty different APIs, so their implementations differ moderately, but the main idea is the same.

Bunny and the Java client are good examples to follow (in fact, replicate).

**Comment by michaelklishin** [comment] 2015-07-29 22:24
Overall the ideas in Bunny and Java client have worked well for multiple clients in pretty different languages:

 * Ruby (amqp gem, Bunny, March Hare)
 * Java
 * C#
 * Clojure (Langohr, previously with a pure Clojure implementation, now based on the Java client)

**Comment by squaremo** [comment] 2015-07-29 22:38
My desiderata:

 * auto-recovery is explicitly optional
 * user pays -- where there's a cost, you only pay it if you've switched recovery on
 * no relying on internal state, please

**Comment by michaelklishin** [comment] 2015-07-29 22:43
Recovery is currently opt-in in Java and .NET clients. It is opt-out in Bunny. We haven't heard complaints about either decision but I agree.

What do you mean by not relying on internal state?

**Comment by squaremo** [comment] 2015-07-29 22:47
> What do you mean by not relying on internal state?

Anything but using the public mechanisms available; e.g., no examining buffers or spoofing channel numbers. I'm not ruling out *maintaining* bookkeeping state -- it'd be a bit tricky otherwise. And there may be exceptions where it's simply impossible to do something any other way.

**Comment by michaelklishin** [comment] 2015-07-29 23:00
Agreed. Only a few bits of extra state should be necessary — messing with buffers or sockets beyond detecting network failures should not be necessary.

**Comment by rikaardhosein** [comment] 2015-07-29 23:04
My work on this is stalled until Saturday. I'll review these comments in
more detail then. Thanks!

**Comment by jwalton** [comment] 2015-08-21 22:48
Ok, I've taken a stab at fixing this whole reconnection problem.  Check out https://github.com/benbria/node-amqp-connection-manager and see if it solves your use case.  If it doesn't, or if you have suggestions, I'm certainly interested in hearing about it.  :)

**Comment by cressie176** [comment] 2016-04-09 17:24
[Rascal](https://github.com/guidesmiths/rascal) also supports connection recovery. It doesn't do any of the clever write ahead stuff discussed in #25, just simply reconnects, reasserts and resubscribes.

**Comment by sokardys** [comment] 2016-06-16 11:02
+1

**Comment by EmrysMyrddin** [comment] 2020-09-16 09:46
Is this still a wanted feature ?

It seems lot of other clients handles this. The Java implementation even enables it by default now.

**Comment by salamander-mh** [comment] 2020-12-11 09:31
the feature is very import!!!

**Comment by cressie176** [comment] 2022-05-05 18:30
Duplicate of https://github.com/amqp-node/amqplib/issues/25

**Closed by cressie176** 2022-05-05 18:30 UTC
