### ISSUE TITLE
Publish confirm callback not called

### ISSUE THREAD

**Issue by diegomansua** [amqp-node/amqplib#419] opened 2018-05-05 09:26 UTC
Hi,

I have something like this, using a confirm channel:

```
server.post('/test', async (req, res) => {
  const message = Buffer.from(JSON.stringify(req.body));

  await new Promise((resolve, reject) => channel.publish('test', 'test', message, {persistent: true}, (error) => {
    if (error) {
      console.error('Error publishing', error);

      return reject(error);
    }

    return resolve();
  }));

  return res.status(204).end();
});
```
The problem is that if I send a request after getting disconnected from the server (literally pulling the network cable) but before the heartbeat detects the connection issue, the callback is never called and thus I'm not sending a response back. I do get an 'error' event on my connection, though.

I would expect the confirm callback to be called with an error.

Maybe it'd be interesting to have a timeout for publish confirms as well? At the moment I'm thinking of implementing a timeout mechanism using `Promise.race` to send an error response.

Thanks.

**Comment by diegomansua** [comment] 2018-05-05 12:02
By the way, this is more or less what I'm doing now: I'm using the same callback for the publish confirm and to handle connection errors. Then when the callback is called I remove the listener from the connection.

```
server.post('/test', async (req, res) => {
  const message = Buffer.from(JSON.stringify(req.body));

  await new Promise((resolve, reject) => {
    const callback = (error) => {
      connection.removeListener('error', callback);

      if (error) {
        console.error('Error publishing', error);

        return reject(error);
      }

      return resolve();
    };

    connection.on('error', callback);
    channel.publish('test', 'test', message, {persistent: true}, callback);

    return res.status(204).end();
  });
});
```

**Comment by michaelklishin** [comment] 2018-05-15 23:51
I see no evidence of confirms being used here. A [traffic capture](http://www.rabbitmq.com/amqp-wireshark.html) will immediately reveal if that's the case and whether they are sent.

An executable way to reproduce would really help, too.

**Comment by diegomansua** [comment] 2018-05-18 07:08
Thanks a lot for your reply.

There are no network traffic to capture, because there's no network. :)

I'm trying to test error handling scenarios. Sequence of actions:

- Connect normally
- Unplug network cable/forcibly disconnect from network
- Try to publish a message with confirmation (i.e. passing a callback)
- Heartbeat detects loss of connection -> error event on channel

The confirmation callback is not called. I think it'd be nice if it was called with an error in this scenario, as the connection was lost and confirmation will never arrive (actually in this case the message was not even published).

This is because I'm guessing it's a common scenario out there to respond to an HTTP request after the message has been acknowledged as published, i.e. within the confirm callback (like in my first example). If the confirmation callback is not called then the HTTP request will remain open.

**Comment by kletkeman** [comment] 2018-05-27 15:34
I think what he meant was that you are not calling waitForConfirms(), which will wait until rabbit can guarantee that something will happen with your message ...

**Comment by squaremo** [comment] 2018-05-28 22:38
It's a tricky call. Confirms (and nacks) are supposed to indicate the fate of messages. If you pull the network cable, you shouldn't expect to learn the fate of the messages either way (there may have been confirmations on their way to you that got stranded in the network! Or nacks). The loss of the connection means you will get no more information, not that everything you haven't heard yet about has failed.

You may want to assume that any messages that were unconfirmed, at the time you learned that the server was unavailable, were dropped. You may want to assume that they were sent. If the confirm callbacks are called with an error before you're told about the connection failing, you won't get to make that choice.

In the case of the HTTP request: yes, you will have to use some kind of timeout. Say you were calling some internal service via HTTP again, rather than through RabbitMQ. It might take a while to respond, and you would have to decide whether you give up at some point and treat it as a failure, even though it might have succeeded and just not told you yet. It's the same deal here.

**Comment by tnesuett** [comment] 2018-09-18 00:39
Sorry for resurrecting this thread...
Totally get the dilemma, but is there a way in this case to reject the unconfirmed promises with a 'cancelled' error? This would let the user know what they are on their own as to the fate of the messages, but at lease there is some resolution (no pun intended.)
Otherwise, there could possibly be a number of dangling promises using up resources -- if I understand node correctly.

**Comment by squaremo** [comment] 2018-09-19 21:28
> Totally get the dilemma, but is there a way in this case to reject the unconfirmed promises with a 'cancelled' error?

Signalling "fate unknown" explicitly is an interesting idea. I struggle a bit to know how to fit it into the Promise contract in a backward-compatible way -- is it an error, in which case code which assumes errors mean failure break; or is it a success failure, which has the analogous problem.

**Comment by tnesuett** [comment] 2018-09-20 00:18
Good point about backward compatibility. How about an option. Something like:

`nackUnconfirmedOnClose: <defaults to false>`

If users turn this feature on, then they should expect an error that is not really an error. Of course the wording on the option could be something else so not to overload the 'nack' term.
Another alternative would be to either expose the `unconfirmed` array or have a `nackUnconfirmed()` method. Both of these sound too hacky though and open up the lib to mis-use.

**Comment by tnesuett** [comment] 2018-09-20 06:49
Actually, after some experimenting, the idea of an extra call sounds more appealing. Something along these lines (channel_model.js):
```
// Flushes any unconfirmed messages by calling
// the (optional) callback with 'error'.
CC.flushUnconfirmed = function(error) {
  while(this.unconfirmed.length > 0) {
    let u = this.unconfirmed.shift();
    if (u) u(error);
  }
}
```
This way, I can control exactly when I want to flush my pending confirms. My worry earlier was that someone would call this method in the middle of a live connection, but most people are over 18 and vaccinated. i.e. they are responsible for their actions.
This solved my last issue (famous last words) with adding re-connect logic.

**Comment by wallride** [comment] 2019-07-03 11:56
I got similar problem with never-resolving confirmation callback when connection is closed while publishing a message.
I understand that it's impossible to get ack/nack confirmation even after reconnect (due to deliveryTag is unique only within a channel AFAIK).
And I believe that callback MUST resolve with an error (or more informative object) when connection is broken.

**Comment by hardcodet** [comment] 2019-07-22 18:57
> It's a tricky call. Confirms (and nacks) are supposed to indicate the fate of messages. If you pull the network cable, you shouldn't expect to learn the fate of the messages either way (there may have been confirmations on their way to you that got stranded in the network! Or nacks). The loss of the connection means you will get no more information, not that everything you haven't heard yet about has failed.

@squaremo  Actually, this hangs even if I sever the connection to RabbitMQ shortly _before_ publishing - so the library would actually know nothing was sent. And yet `waitForConfirms` is hanging, and the callback ins `publish` do not get called. I could set a timeouts on `connect`, but apparently not on any other operation although they are network calls as well?

> 
> You may want to assume that any messages that were unconfirmed, at the time you learned that the server was unavailable, were dropped. You may want to assume that they were sent. If the confirm callbacks are called with an error before you're told about the connection failing, you won't get to make that choice.

> 
> In the case of the HTTP request: yes, you will have to use some kind of timeout. Say you were calling some internal service via HTTP again, rather than through RabbitMQ. It might take a while to respond, and you would have to decide whether you give up at some point and treat it as a failure, even though it might have succeeded and just not told you yet. It's the same deal here.

But shouldn't `publish` (or any other operation) time out eventually. If I await `waitForConfirms` this will hang forever, and I'll never get an invocation for the callback (probably same problem with internal hangs, which would probably also cause memory leaks.

IMO, from the client's view, this is an erroneous condition in any case. Message loss is the big imperative, so I would always treat "maybe" having lost a message as "having lost" a message (and risk a message being published twice, with idempotency on the receiver end).

**Comment by hardcodet** [comment] 2019-07-22 19:27
@squaremo I searched the code for timeouts, and stumbled over that line here:

      // disable timeout once the connection is open, we don't want
      // it fouling things
      if (timeout) sock.setTimeout(0);

Removing this caused my calls to fail as I'd expect them, rather than causing every single call to hang forever.

However. :)
I noticed that if I set the timeout to 5000 (which is incredibly high given that my "server" is running in a local container), the heartbeats start wreaking havoc, reconnects break, etc. (see stack trace below). Increasing it to 10000 fixed those issues, but I wouldn't know how the 5000 would be an issue given that my latency is basically inexistent. Not sure this is a red flag, or just beyond my limited Node skills, but it looks like a tradeoff between the lesser of two evils 💀 

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[0]     at writeAfterEnd (_stream_writable.js:248:12)
[0]     at Socket.Writable.write (_stream_writable.js:296:5)
[0]     at Connection.C.sendBytes (C:\Users\sumiph\Dropbox\Projects\Dormakaba\Repositories\Resido.API.Node\node_modules\amqplib\lib\connection.js:519:15)
[0]     at Connection.C.sendHeartbeat (C:\Users\sumiph\Dropbox\Projects\Dormakaba\Repositories\Resido.API.Node\node_modules\amqplib\lib\connection.js:523:15)
[0]     at Heart.<anonymous> (C:\Users\sumiph\Dropbox\Projects\Dormakaba\Repositories\Resido.API.Node\node_modules\amqplib\lib\connection.js:433:12)
[0]     at Heart.emit (events.js:198:13)
[0]     at Heart.runHeartbeat (C:\Users\sumiph\Dropbox\Projects\Dormakaba\Repositories\Resido.API.Node\node_modules\amqplib\lib\heartbeat.js:88:17)
[0]     at ontimeout (timers.js:436:11)
[0]     at tryOnTimeout (timers.js:300:5)
[0]     at listOnTimeout (timers.js:263:5)
[0]     at Timer.processTimers (timers.js:223:10)
[0] ERROR: RabbitService --> RabbitMQ connection error connection.close (error #2). Will try to reconnect. 
```

**Comment by hardcodet** [comment] 2019-07-23 16:05
@squaremo I filed a PR that just introduces a second timeout setting that is being applied after the initial connection. It's not beautiful, but IMO still better than callbacks that are never being invoked, or promises hanging forever.

```
// connect with timeout (otherwise hangs indefinitely if the broker is unavailable)
this.connectionPromise = this.amqp.connect(options, { timeout: 5000, postConnectTimeout: 20000 });
```

If not set, a default timeout of 300'000 ms is being applied. Setting `0` would have made the PR completely neutral (no change in behavior if not set), but I don't think anybody would argue with a request breaking after 5 minutes of not getting any response ;). I can still change that to a default of 0, of course and introduce the "old" behavior again as a default.

Thanks for your consideration!

**Comment by cressie176** [comment] 2022-05-06 18:32
Duplicate of https://github.com/amqp-node/amqplib/issues/419

**Closed by cressie176** 2022-05-06 18:32 UTC
