### ISSUE TITLE
Consider removing `readable-stream`?

### ISSUE THREAD

**Issue by jimmywarting** [amqp-node/amqplib#729] opened 2023-06-25 17:53 UTC
I would like it if `readable-stream` didn't have to be installed / downloaded.
they don't seem to be used much at all...
it looks like this everywhere:
```js
require('stream').<x> || require('readable-stream/<x>') 
```
is it okey to remove it?

**Comment by cressie176** [comment] 2023-07-14 05:56
I think you're right. I'll try removing and running with Node 10.

**Comment by cressie176** [comment] 2024-11-24 10:21
Removed. Thanks @jimmywarting

**Comment by lobokoch** [comment] 2024-12-03 14:49
After I updated from version amqplib: 0.10.3 to amqplib: 0.10.5, when I run my application I got the error: (node:31412) UnhandledPromiseRejectionWarning: Error: Cannot find module 'readable-stream'.

**Comment by cressie176** [comment] 2024-12-03 19:30
Thanks for the report @lobokoch, I'll try running the tests with that node version and see what happens

**Comment by cressie176** [comment] 2024-12-03 19:56
@lobokoch I've run the tests using node v20.15.0 and the run fine. I've also grep'd the code base and the string 'readable-stream' only appears in a single comment, so nothing in amqplib 0.10.5 can be requiring it. Is it possible some other code in your application is relying on readable-stream being installed by amqplib, and now that it is has been removed is failing? 

What  does the stacktrace show?

**Comment by cressie176** [comment] 2024-12-06 23:01
Closing on assumption that the issue is something other than amqplib is dependent on readable-stream but has not declared it as a dependency.

**Closed by cressie176** 2024-12-06 23:01 UTC
