### ISSUE TITLE
Trying to Channel#get on a non-existing queue takes down entire process

### ISSUE THREAD

**Issue by LinusU** [amqp-node/amqplib#282] opened 2016-09-22 10:38 UTC
The following minimal example will crash the process with unhandled 'error' event instead of rejecting the promise returned from `Channel#get`.

``` js
const amqp = require('amqplib')
const open = amqp.connect('amqp://localhost')

open.then(connection => {
  return connection.createChannel()
}).then(channel => {
  return channel.get('there-is-no-queue-with-this-name')
}).then(
  () => console.log('Did not get any error'),
  () => console.log('Got an error')
)
```

**Comment by connec** [comment] 2016-09-22 11:10
I can't find an explicit reference to this in the AMQP docs, but that's generally how the protocol works: the channel gets blown away when errors occur. You could check your RabbitMQ log to see if that's what's happening.

In general, you avoid this by calling `assertQueue` before attempting to use a queue. It is an idempotent operation so there's no harm doing it at both 'ends' of an RPC.

**Comment by michaelklishin** [comment] 2016-09-22 11:12
I think the point is that a channel exception should reject the promise instead of letting the exception bubble up, not that the error is unexpected.

**Comment by LinusU** [comment] 2016-09-22 11:14
Exactly what @michaelklishin said, I'm having problem with handling errors in a controlled manner since the error is not reported back to the `.get` call, but instead is emitted on the channel.

I don't want to `.assertQueue` since I don't want the queue to be created if it doesn't exists. I want to return an error to my consumer, stating that the queue they requested doesn't exists.

**Comment by connec** [comment] 2016-09-22 13:17
In that case you could use `.checkQueue`, though the error will still be thrown on the channel.

I just had a quick look at the code, you might find the rejection will be processed if you attach a no-op 'error' handler to the channel. Unfortunately I can't check it myself right now.

**Comment by LinusU** [comment] 2016-09-22 13:53
Using `.checkQueue` would introduce race conditions though, the queue could be removed in between my call to `checkQueue` and `get`.

Adding a listener to the `error` event will actually allow the `.get` call to reject. It doesn't reject with an `Error` instance though. I really don't want to ignore any errors on the channel since that could hide other errors.

**Comment by AlexTes** [comment] 2016-10-19 15:41
I think this is a dupe of #266 .

**Comment by squaremo** [comment] 2017-05-04 06:52
> I think the point is that a channel exception should reject the promise instead of letting the exception bubble up, not that the error is unexpected.

Regrettably, the protocol mandates that the channel is closed, and that's what the server does. So, even if this library carefully handled the error for you, and rejected the promise, the channel you had been using to that point would still be invalid.

If you are doing operations that might fail, you just have to prepare for the channel to emit an error, and restart whatever you were doing. Workarounds like that linked above (thanks Alex) can help. I wish I had a better, general solution but I lack the imagination (and at the minute, time). Sorry!

**Closed** 2022-05-04 23:04 UTC
