### ISSUE TITLE
connect() calls its own callback multiple times upon error

### ISSUE THREAD

**Issue by dotkas** [amqp-node/amqplib#354] opened 2017-05-24 17:18 UTC
Hello.

If I try to connect to a queue using invalid credentials, such as this:
```
amqp.connect(config.endpoints.textQueue + '?heartbeat=30', (err, conn) => {
    if (err) {
        return callback(`Unable to connect to rabbitMQ (${url.parse(config.endpoints.textQueue).host}), is there a connection? Aborting: ${err}`);
    }
(...)
}
```

The callback is called two times with an `err` parameter. First one that gives me access denied, and then one with a socket close.

This obviously causes my code to throw an exception due to the callback already having been called.

Is this working as intended?

First callback:
`Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"`

Second:
`Socket closed abruptly during opening handshake`

Thank you in advance.

**Comment by cressie176** [comment] 2017-05-25 19:08
I get the same. Looks like a bug. Could be fixed by wrapping [openCallback]
(https://github.com/squaremo/amqp.node/blob/master/lib/connect.js#L99) so that it only ever is executed once, or by checking / setting a flag wherever openCallback is called, however both of these solutions would mean suppressing socket errors that occurred after successfully connecting. @squaremo thoughts?

**Comment by cressie176** [comment] 2017-07-31 07:34
I suspect this is the root cause of https://github.com/guidesmiths/rascal/issues/17

**Comment by tcort** [comment] 2017-08-21 19:14
I ran into this issue as well. As a work around, I used `_.once(fn)` to wrap the callback I passed to `amqp.connect()` as described here: https://github.com/guidesmiths/rascal/issues/17#issuecomment-319008663

**Comment by cressie176** [comment] 2017-11-20 21:26
This seems better in 0.5.2, however I'm I've just hit a similar problem with errors returned from `connection.createChannel`.

### Steps to reproduce
1. Create Connection
2. Create Channel
3. Subscribe (without optional callback)
4. Close connection

If the subscription hasn't complete by the time the connection is closed, amqplib executes the create channel callback multiple times.

**Comment by AbdulRahmanAlHamali** [comment] 2021-11-29 16:09
This bug, combined with the retry code presented here:

https://www.cloudamqp.com/docs/nodejs.html

Can DDoS RabbitMQ. It's a shame it hasn't been addressed yet

**Comment by cressie176** [comment] 2022-05-08 21:48
Duplicate of https://github.com/amqp-node/amqplib/issues/402

**Closed by cressie176** 2022-05-08 21:48 UTC
