### ISSUE TITLE
assertQueue() never returns

### ISSUE THREAD

**Issue by blissi** [amqp-node/amqplib#429] opened 2018-06-12 19:31 UTC
Hallo,
I've got a strange problem:
Usually the following, stripped down code just works:
```
const rabbit = require('amqplib');

const connection = rabbit.connect('amqp://localhost:5672');
const queue = 'mycommands';

connection
	.then((con) => con.createChannel())
	.then(async (ch) => {
		try {
			console.log("Asserting queue now...");
			await ch.assertQueue(queue);
			console.log("Queue successfully asserted!");
			return ch;
		}
		catch (err) {
			console.error("Failed: " + err);
		}
	});
```

But sometimes the promise of assertQueue is never completed - neither successfully nor rejected - and therefore the code just hangs. I can restart my application over and over again and this bug always remains. When I change the queue name to one that is not present yet in my RabbitMQ-server, the problem still remains, but when I enter the RabbitMQ management console I can see that the new queue has been created.

When I restart the RabbitMQ service, the problem is gone - therefore this might not be a problem of amqplib, but of RabbitMQ itself. I am using RabbitMQ 3.6.12 under Windows and amqplib 0.5.2. But I also experienced problems under our production server (Linux on Google Cloud), but at the moment it is just a strong assumption and not evidenced by debugging. Has anybody experienced such a problem, too? Do you have an idea what's going on or how this could be fixed?

**Comment by squaremo** [comment] 2018-06-12 21:56
You could try tracing* frames as they come in on the connection, that will at least tell you whether RabbitMQ sends a reply.
(*i.e., a tactically-placed console.log)

**Comment by blissi** [comment] 2018-06-14 05:38
I receive heartbeat frames, but no answer for the assertQueue.

**Comment by squaremo** [comment] 2018-06-17 11:55
I'm not aware of anyone getting no response back from an RPC, and the code example looks innocuous.
Perhaps you could see what RabbitMQ thinks is happening in a bit more detail, by changing its log level: https://www.rabbitmq.com/logging.html (you may need to find older docs if you're using 3.6)

**Comment by svengau** [comment] 2018-12-06 02:48
@blissi I've got the same issue than you, usually after an Heartbeat timeout. Did you find a solution ? Thanks

**Comment by blissi** [comment] 2018-12-07 07:58
@svengau No, I even didn't have a clue under which conditions this happens...so good to hear that you may have found the cause. Is this reproducible?

**Comment by svengau** [comment] 2018-12-07 08:03
@blissi I've tried to reproduce the issue, without success.

I've finally done an ugly patch by forcing the promise to time out, using the package p-timeout.

**Comment by blissi** [comment] 2018-12-07 09:20
@svengau  Can you attach the patch here? Thanks in advance!

**Comment by svengau** [comment] 2018-12-07 09:53
Sure.

```
   const pTimeout = require('p-timeout');
   const TIMEOUT = 2000; // millisec
   
    const connection = await pTimeout(amqp.connect({ ... }), TIMEOUT);
    logging.info(`Creating channel`);
    const channel = await pTimeout(connection.createChannel(), TIMEOUT);
    logging.info(`Channel created`);
    const q = await pTimeout(channel.assertQueue('', { exclusive: false }), TIMEOUT);
    logging.info(`Connected to broker`);
```

**Comment by blissi** [comment] 2018-12-07 09:54
Thank you!

**Comment by amolkedar** [comment] 2019-01-23 18:12
Hey guys we are experiencing something very similar in our production environment too, we don't get a response back on the assertQueue and this causes the application code to hang, i will try more logging on the rabbitMQ, but the rabbitMQ CPU utilization, memory utilization and load average all are under the thresholds We use rabbit 3.7.8

**Comment by squaremo** [comment] 2019-01-23 22:09
Has anyone managed to get RabbitMQ to log the frames / commands it gets?

**Comment by amolkedar** [comment] 2019-01-23 22:18
Hi @squaremo Thanks for the reply, how do we log it? is it a server setting on rabbitmq ? or is there a setting from the amqp library to print it to the logs?

**Comment by squaremo** [comment] 2019-01-23 22:23
The docs at https://www.rabbitmq.com/logging.html tell you how to change the log level, but not what it gets you. I'd _hope_ that setting the level to `debug` (or `trace`?) would result in the received and sent frames being recorded.

**Comment by akang1** [comment] 2019-01-25 16:47
hi @squaremo, I work with @amolkedar and I changed the log level to output debug logs 

"log.file.level = debug"

I will look at the logs during the time the potential error occurs in our application, but i was wondering if there is anything specific I should look for in the logs when the error occurs and also, before the  error happens?

**Comment by cressie176** [comment] 2022-05-04 22:25
Closing due to age. For anyone reading this with similar issues, I also suggest using [wireshark to sniff amqp packets](https://www.rabbitmq.com/amqp-wireshark.html) between a local application and the broker experiencing the problem if possible. I should be quite clear from comparing a successful queue assert with an unsuccessful one whether the issue is with client or server/network.

**Closed by cressie176** 2022-05-04 22:25 UTC
