### ISSUE TITLE
Socket closed abruptly during opening handshake

### ISSUE THREAD

**Issue by mateodelnorte** [amqp-node/amqplib#101] opened 2014-10-06 20:30 UTC
Client fails to connect with error `Socket closed abruptly during opening handshake` and no apparent error or auth rejection is shown in RabbitMQ's logs:

```
=INFO REPORT==== 6-Oct-2014::09:06:08 ===
accepting AMQP connection <0.32242.0> (127.0.0.1:63772 -> 127.0.0.1:5672)

=INFO REPORT==== 6-Oct-2014::09:06:23 ===
accepting AMQP connection <0.32254.0> (127.0.0.1:63783 -> 127.0.0.1:5672)

=INFO REPORT==== 6-Oct-2014::09:06:23 ===
accepting AMQP connection <0.32257.0> (127.0.0.1:63786 -> 127.0.0.1:5672)
```

Using amqplib@0.2.1. Only goes away after restarting RabbitMQ.

**Comment by squaremo** [comment] 2015-01-10 17:42
@mateodelnorte Any joy (/despair) trying to reproduce this, or more data on the failures?

**Comment by mateodelnorte** [comment] 2015-01-13 15:17
I haven't seen it pop up on its own in quite a while, but I also haven't
had a chance to try and isolate it. What I can say is that it only appeared
to happen on my development environment when my macbook went into sleep /
hibernate mode with the lid closed.

**Comment by mateodelnorte** [comment] 2015-02-02 03:56
Started seeing this again (after re-awaking my macbook): 
```
Potentially unhandled rejection [2] Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/Users/matt/development/electronifie/electronifie/market-config-svc/node_modules/servicebus/node_modules/amqplib/lib/connection.js:249:17)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```
endWhileOpening(err) is getting called from this.stream.on('end'... at line 252: 
```
  // If the server closes the connection, it's probably because of
  // something we did
  function endWhileOpening(err) {
    console.log(err)
    bail(err || new Error('Socket closed abruptly ' +
                          'during opening handshake'));
  }

  this.stream.on('end', endWhileOpening);
```
It looks like this is a problem with RabbitMQ. Not sure what's putting it into this state, but reloading the management console show the following error: 
```
Got response code 500 with body {"error":"Internal Server Error","reason":"{error,\n {error,\n {badmatch,{error,nxdomain}},\n [{rabbit_nodes,cluster_name_default,0,\n [{file,\"src/rabbit_nodes.erl\"},{line,195}]},\n {rabbit_nodes,cluster_name,0,\n [{file,\"src/rabbit_nodes.erl\"},{line,190}]},\n {rabbit_mgmt_wm_overview,to_json,2,\n [{file,\"rabbitmq-management/src/rabbit_mgmt_wm_overview.erl\"},\n {line,43}]},\n {webmachine_resource,resource_call,3,\n [{file,\n \"webmachine-wrapper/webmachine-git/src/webmachine_resource.erl\"},\n {line,186}]},\n {webmachine_resource,do,3,\n [{file,\n \"webmachine-wrapper/webmachine-git/src/webmachine_resource.erl\"},\n {line,142}]},\n {webmachine_decision_core,resource_call,1,\n [{file,\n \"webmachine-wrapper/webmachine-git/src/webmachine_decision_core.erl\"},\n {line,48}]},\n {webmachine_decision_core,decision,1,\n [{file,\n \"webmachine-wrapper/webmachine-git/src/webmachine_decision_core.erl\"},\n {line,558}]},\n {webmachine_decision_core,handle_request,2,\n [{file,\n \"webmachine-wrapper/webmachine-git/src/webmachine_decision_core.erl\"},\n {line,33}]}]}}\n"}
```
which is also in the logs: 
```
=ERROR REPORT==== 1-Feb-2015::22:42:38 ===
webmachine error: path="/api/nodes"
{error,
    {error,
        {badmatch,{error,nxdomain}},
        [{rabbit_nodes,cluster_name_default,0,
             [{file,"src/rabbit_nodes.erl"},{line,195}]},
         {rabbit_nodes,cluster_name,0,
             [{file,"src/rabbit_nodes.erl"},{line,190}]},
         {rabbit_mnesia,status,0,[{file,"src/rabbit_mnesia.erl"},{line,329}]},
         {rabbit_mgmt_wm_nodes,all_nodes_raw,0,
             [{file,"rabbitmq-management/src/rabbit_mgmt_wm_nodes.erl"},
              {line,46}]},
         {rabbit_mgmt_wm_nodes,all_nodes,1,
             [{file,"rabbitmq-management/src/rabbit_mgmt_wm_nodes.erl"},
              {line,43}]},
         {rabbit_mgmt_wm_nodes,to_json,2,
             [{file,"rabbitmq-management/src/rabbit_mgmt_wm_nodes.erl"},
              {line,34}]},
         {webmachine_resource,resource_call,3,
             [{file,
                  "webmachine-wrapper/webmachine-git/src/webmachine_resource.erl"},
              {line,186}]},
         {webmachine_resource,do,3,
             [{file,
                  "webmachine-wrapper/webmachine-git/src/webmachine_resource.erl"},
              {line,142}]}]}}
```
What's strange is that subsequently connecting via amqplib and node *does not* cause any errors in the RabbiqMQ logs. Just a normal accepted connect:
```
=INFO REPORT==== 1-Feb-2015::22:44:11 ===
accepting AMQP connection <0.1185.2> (127.0.0.1:63193 -> 127.0.0.1:5672)
```
Guessing this is a RabbitMQ issue, but it's pretty hard to spelunk...

**Comment by mateodelnorte** [comment] 2015-05-06 21:35
I'm now seeing this every time I restart rabbitmq. It's especially insidious because the error occurs in all my processes, but never trigger process.on('uncaughtException'. So, I get a giant error. The channel goes dead, but the process doesn't bounce. Worst case scenario. I can listen to 'error' on the channel and then do a process.abort(1), but that's super ugly. I want to just throw it and let 'uncaughtException' handle it the same as all other errors. 

I think I've tracked this down to a potentially unhandled rejection coming out of 'when.js's unhandledRejection.js. I'm wondering if this is a bug in channel_models.js' use of when....

Thoughts?

**Comment by mateodelnorte** [comment] 2015-05-06 21:40
Currently tried with node 0.10 and 0.12. Also doesn't trigger unhandledRejection on iojs 1.8.1.

**Comment by squaremo** [comment] 2015-05-06 21:44
Do you think this indicates amqplib is swallowing a rejection somewhere? e.g., something like

    return somePromise(onsucceed, noop);

**Comment by mateodelnorte** [comment] 2015-05-06 21:48
What I'm finding is that when's `report` is being called, but I haven't tracked down *where* it's being called yet. 

https://github.com/cujojs/when/blob/master/lib/decorators/unhandledRejection.js#L32-L47

So it appears it's reporting, but not throwing. ... perhaps.

**Comment by mikeatlas** [comment] 2015-07-21 19:40
This might be a little crazy, but I hit this same error and it turned out my URI needed "extra" vhost prefix slash:

```javascript
var rabbitURI = 'amqps://' + process.env.RABBITMQ_USER + ':' + process.env.RABBITMQ_PW;
rabbitURI += '@' + process.env.RABBIT_HOST + ':' + process.env.RABBITMQ_PORT;
rabbitURI += '/' + process.env.RABBITMQ_VHOST;
```

where he `RABBITMQ_VHOST` environment variable is also set with the prefix `/`, like `RABBITMQ_VHOST=/myvhost`.

**Comment by michaelklishin** [comment] 2015-07-21 20:40
vhost names in URIs must be [percent encoded](https://en.wikipedia.org/wiki/Percent-encoding), as mentioned in [RabbitMQ documentation](https://www.rabbitmq.com/uri-spec.html).

**Comment by mikeatlas** [comment] 2015-07-21 21:37
@michaelklishin Understood; `RABBITMQ_VHOST=/%2Fmyvhost` might be "most" appropriate depending on how one builds a URI string... but I'll still assert that I saw different connection behavior (the error message in the OP) between two different instances of Rabbit and the same code; workaround in my case was, like you're saying, ensure that the vhost path is URL encoded within the URI itself as well.

**Comment by sudogem** [comment] 2016-02-01 10:22
`sdfsdfdfdf dsf dsfdf`

**Comment by mehnaazm** [comment] 2017-04-05 12:56
Im getting the same error : 
Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/node_modules/amqplib/lib/connection.js:258:17)

RabbitMQ Setup 
- 2 nodes cluster . from the RabbitMQ sites documentation of cluster [no mirroring]
HA-Proxy 
- talking with both the servers 

Node Code: 
Running infinitely to send messages using 10 connections . every second 
after some time when i run "sudo rabbitmq-server stop" on the master cluster . 
My code gives this error upon trying to retry.

**Comment by michaelklishin** [comment] 2017-04-05 13:02
@squaremo this issue is becoming a honey pot for unrelated network connection issues. I think it should be closed as there is no evidence that something in this client is obviously wrong.

**Comment by michaelklishin** [comment] 2017-04-05 13:06
I haven't noticed this claim by the OP:

> Don't think so. Should be set to unlimited

I am unaware of a way to set the open file handle limit to "unlimited". Even if that's possible, as far as RabbitMQ log (and an empty SASL log) is concerned, the connection was never accepted (if it was it then sent no data).

@mehnaazm if you have a way to reproduce this, [take a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) and see what's going on with the TCP connection. Also see server logs. It is impossible to suggest anything specific with the amount of information provided.

**Comment by mehnaazm** [comment] 2017-04-05 13:24
@michaelklishin  i can reproduce it easily .
[masterRabbit.txt](https://github.com/squaremo/amqp.node/files/896335/masterRabbit.txt)
[slaveRabbit.txt](https://github.com/squaremo/amqp.node/files/896336/slaveRabbit.txt)

 here are the server logs.  i cleaned the logs before running the code. 

Note that im only stopping the master server.

**Comment by michaelklishin** [comment] 2017-04-05 13:29
There are no master or mirror nodes in RabbitMQ. Queues have a master and 0+ mirrors, nodes are all equal. So for the purpose of this discussion let's call them N1 and N2.

N1 shuts down and force closes 4 connections it had, as expected:

```
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping application 'rabbit'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
stopped TCP Listener on [::]:5672

=ERROR REPORT==== 5-Apr-2017::18:48:48 ===
Error on AMQP connection <0.542.0> (17.15.3.193:48548 -> 17.15.3.213:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"

=ERROR REPORT==== 5-Apr-2017::18:48:48 ===
Error on AMQP connection <0.545.0> (17.15.3.193:48550 -> 17.15.3.213:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"

=ERROR REPORT==== 5-Apr-2017::18:48:48 ===
Error on AMQP connection <0.548.0> (17.15.3.193:48552 -> 17.15.3.213:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"

=ERROR REPORT==== 5-Apr-2017::18:48:48 ===
Error on AMQP connection <0.551.0> (17.15.3.193:48554 -> 17.15.3.213:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"

=ERROR REPORT==== 5-Apr-2017::18:48:48 ===
Error on AMQP connection <0.538.0> (17.15.3.193:48546 -> 17.15.3.213:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation none caused a connection exception connection_forced: "broker forced connection closure with reason 'shutdown'"

=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping message store for directory '/var/lib/rabbitmq/mnesia/rabbit@anudeepthi-Vostro-3558/msg_store_persistent'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Message store for directory '/var/lib/rabbitmq/mnesia/rabbit@anudeepthi-Vostro-3558/msg_store_persistent' is stopped
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping message store for directory '/var/lib/rabbitmq/mnesia/rabbit@anudeepthi-Vostro-3558/msg_store_transient'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Message store for directory '/var/lib/rabbitmq/mnesia/rabbit@anudeepthi-Vostro-3558/msg_store_transient' is stopped
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping application 'mnesia'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping application 'rabbit_common'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Stopping application 'os_mon'
=INFO REPORT==== 5-Apr-2017::18:48:48 ===
Successfully stopped RabbitMQ and its dependencies
```

N2 observes that N1 disconnected, then accepts a few connections, then observes 10 cases of client connections closing TCP connection and one properly closing AMQP 0-9-1 connection:

```
=INFO REPORT==== 5-Apr-2017::18:48:49 ===
rabbit on node 'rabbit@anudeepthi-Vostro-3558' down

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
accepting AMQP connection <0.725.0> (17.15.3.193:33796 -> 17.15.3.163:5672)

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
accepting AMQP connection <0.728.0> (17.15.3.193:33798 -> 17.15.3.163:5672)

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
accepting AMQP connection <0.731.0> (17.15.3.193:33800 -> 17.15.3.163:5672)

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
Keep rabbit@anudeepthi-Vostro-3558 listeners: the node is already back

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
connection <0.725.0> (17.15.3.193:33796 -> 17.15.3.163:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
connection <0.728.0> (17.15.3.193:33798 -> 17.15.3.163:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
connection <0.731.0> (17.15.3.193:33800 -> 17.15.3.163:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
accepting AMQP connection <0.760.0> (17.15.3.193:33802 -> 17.15.3.163:5672)

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
connection <0.760.0> (17.15.3.193:33802 -> 17.15.3.163:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
accepting AMQP connection <0.771.0> (17.15.3.193:33804 -> 17.15.3.163:5672)

=INFO REPORT==== 5-Apr-2017::18:48:49 ===
connection <0.771.0> (17.15.3.193:33804 -> 17.15.3.163:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 5-Apr-2017::18:48:50 ===
node 'rabbit@anudeepthi-Vostro-3558' down: connection_closed

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.771.0> (17.15.3.193:33804 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.725.0> (17.15.3.193:33796 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.678.0> (17.15.3.193:33777 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.681.0> (17.15.3.193:33781 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.672.0> (17.15.3.193:33775 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.728.0> (17.15.3.193:33798 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.731.0> (17.15.3.193:33800 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.669.0> (17.15.3.193:33773 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection

=WARNING REPORT==== 5-Apr-2017::18:48:52 ===
closing AMQP connection <0.760.0> (17.15.3.193:33802 -> 17.15.3.163:5672):
client unexpectedly closed TCP connection
```

Without having your recovery code and a traffic capture it's difficult to reason about what the client may be doing and why.

**Comment by mehnaazm** [comment] 2017-04-05 13:52
![screen shot 2017-04-05 at 7 07 27 pm](https://cloud.githubusercontent.com/assets/7804502/24708672/2a7cfddc-1a35-11e7-8d76-c715ef46e471.png)
![screen shot 2017-04-05 at 7 07 45 pm](https://cloud.githubusercontent.com/assets/7804502/24708673/2a7ded8c-1a35-11e7-8e6b-5e3ffe383d71.png)

here are the wire shark captures

**Comment by evaisse** [comment] 2017-07-17 16:03
I've found that "pmx" module produce the error in my code. This bug is generated by pmx listen to "data" event on amqplib connection stream. 
I can reproduce this by adding a 

```
  // node_modules/amqplib/lib/connection.js:275
   this.stream.on('data', (chunk) => console.log(chunk));
```

You can also reproduce this using this snippet on top of your application :

```
var pmx = require('pmx').init({
  network       : true, // (default: false) Network monitoring at the application level
});
```

Definitely a problem, should this be handled by pmx ? or it's tied to the way amqplib listen to socket ?

**Comment by michaelklishin** [comment] 2017-07-17 16:24
@evaisse if `pmx` is not a transparent monitoring library, it's their problem, not this client's. PMX cannot expect every project to adapt to them.

**Comment by evaisse** [comment] 2017-07-17 18:32
I partly agree, you're right about the pmx monitoring impact on other modules, but for example, usage of pmx network monitoring in [node-amqp](https://www.npmjs.com/package/amqp) works fine. Mainly because they [restrain usage to stream events](https://github.com/postwait/node-amqp/blob/master/lib/connection.js) instead of [direct stream api calls](https://github.com/squaremo/amqp.node/blob/master/lib/connection.js#L602).
I'm not an expert here, but maybe there is some way to handle amqplib connection api in the same way, only using event ? (probably major changes)

**Comment by lucaswxp** [comment] 2017-12-12 02:00
+1 cant use rabbitmq at all. Any quick workaround?

**Comment by cope** [comment] 2019-06-27 09:16
Same error after rmq was upgraded from 3.5.5 to 3.7.7 :(

**Comment by Fabiomad85** [comment] 2019-12-22 15:42
same error here when I use jest test suite

**Comment by Fabiomad85** [comment] 2020-03-16 10:16
I still have that issue,

**Comment by parkerthegeniuschild** [comment] 2020-08-30 06:24
For any future users who might be having this issue . .  make sure port is set to 5672 ( local amqp  server) and not 15672 (amqp web management console).

**Comment by ramazan-sambapos** [comment] 2021-03-29 15:22
I'm running the docker image like
 "docker run -it --rm --name rabbitmq -p 5672: 5672 -p 15672: 15672 rabbitmq: 3-management"
and problem solved.

[Document](https://www.rabbitmq.com/download.html).

**Comment by ZillionCAdmin** [comment] 2022-02-09 04:01
Hello All,
I'm trying to connect in Node JS with this url:
`amqp://username:password@hostname/vhost`
but i'm getting connect ETIMEDOUT Error. 
when i hit the url with hostname which is **rabbitmq.xyz.com**  in browser, it takes me to login page of rabbitmq and shows me the dashboard. but not able to connect from node js code. How to connect with RabbitMQ when rabbitmq is hosted in server not in local.
Note: I do not want to connect with url amqp://localhost:5672.

**Comment by ramazan-sambapos** [comment] 2022-02-09 08:36
Hi,

I use [amqplib](https://www.npmjs.com/package/amqplib) package for node.js.  

const amqp = require("amqplib/callback_api");

const opt = {
    credentials: require("amqplib").credentials.plain(
      process.env.RABBIT_MQ_USERNAME,
      process.env.RABBIT_MQ_PASSWORD
    ),
};

amqp.connect(
    process.env.RABBIT_MQ_QUEUE_URL,
    opt,
    function (err0, connection) {}
)

Can you check the connection url to connect to the rabbitmq server? When connecting to Rabbitmq server with amqp protocol, a different port is used than the port connected to the admin panel.

Example: (different ports)
Admin Panel : http://hostname:15672
RabbitMQ Server: amqp://hostname:5672

**Closed** 2022-05-05 18:27 UTC

**Comment by vitormaia** [comment] 2022-08-09 15:52
this was exactly the mistake I was making. I was using the same connection port as the manager to connect to the server.

Docker file:

services:
   rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     ports:
       - 15672:15672
       - 5672:5672
     environment:
       - RABBITMQ_DEFAULT_USER=admin
       - RABBITMQ_DEFAULT_PASS=admin

in my connection with node is:

amqp.connect('amqp://admin:admin@localhost:5672/', function(err, connection) {});

and now everything works, thank you very much for the help
