### ISSUE TITLE
Publish returning false: should I send the message again or not?

### ISSUE THREAD

**Issue by TheDanielMoli** [amqp-node/amqplib#713] opened 2023-02-14 12:21 UTC
In my understanding, if the `publish` method returns `false`, it means that the stream is not currently writeable and I must wait for a `drain` event.

When I receive a `drain` event, should I publish the message again?

**Comment by cressie176** [comment] 2023-02-14 13:24
Hi @TheDanielMoli,

There's no need to republish the message, it ends up being buffered - however if your application crashed or you closed the connection without first closing the channels the message would still be lost, so the more messages being buffered the greater the risk. The other reasons to wait until you get the drain event is so that if you're consistently publishing faster than the network / broker can handle, the node process could run out of memory or you could saturate the event loop.

**Comment by TheDanielMoli** [comment] 2023-02-14 13:25
Is there a way to avoid the message being buffered?

**Comment by cressie176** [comment] 2023-02-14 13:29
No - it's not buffered in a deliberate way, it's just how the internals of amqplib work when you publish a message. From memory, messages end up being written into an in memory queue (one per channel), and consumed from those queues using a roughly round robin approach. When amqplib can't write to the broker, it doesn't consume from the queues. I may not be exactly right with the above (it's a long while since I looked at the related code) but I'm close enough.

**Comment by TheDanielMoli** [comment] 2023-02-14 13:34
Thank you! I think that the only way to avoid message loss under catastophic failure is to cache the message before publishing (on a permanent storage, such as a database) and then removing it from the consumer after processing. Do you agree or do you know a better alternative?

**Comment by cressie176** [comment] 2023-02-14 14:49
It somewhat depends on your context. You could just be pushing the problem back a bit. e.g.

1. HTTP REQUEST -> PUBLISH MESSAGE -> HTTP RESPONSE

2. HTTP REQUEST -> SAVE TO DB -> HTTP RESPONSE -> PUBLISH MESSAGE

Both the above scenarios could loose data if an error occurs immediately after receiving the HTTP request. The mitigation is that if a human is initiating the HTTP request by submitting a form, they are aware of the error and can resubmit. Alternatively if it is an upstream system, it also has the option of building in a retry. Therefore, a reasonable general approach off publishing a message, and if you get a "true" back from the publish operation, returning a 501 for **new** HTTP requests until you get a drain event.

**Comment by TheDanielMoli** [comment] 2023-02-14 17:11
@cressie176 What about Publisher Confirms? https://www.rabbitmq.com/tutorials/tutorial-seven-java.html

Are those supported by amqplib?

**Comment by cressie176** [comment] 2023-02-14 18:35
Yes, publisher confirms are supported. You just need to create a confirm channel instead of a regular one, however it's important to understand how and when the confirm will be sent...

From https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed

> For unroutable messages, the broker will issue a confirm once the exchange verifies a message won't route to any queue (returns an empty list of queues). If the message is also published as mandatory, the basic.return is sent to the client before basic.ack. The same is true for negative acknowledgements (basic.nack).
>
> For routable messages, the basic.ack is sent when a message has been accepted by all the queues. For persistent messages routed to durable queues, this means persisting to disk. For [quorum queues](https://www.rabbitmq.com/quorum-queues.html), this means that a quorum replicas have accepted and confirmed the message to the elected leader.

i.e. if the message is delivered, but unroutable you will get a `basic.return` followed by a `basic.ack`. If it is routable, you will get a `basic.ack`

There are no guarantees how long it will take for the broker to send the acknowledgement, and it is possible that the message is delivered, but the `basic.ack` is lost due to network issues etc. Publisher confirms are also considerably slower.


My goto approach for web apps which publish messages is...

1. Publish mandatory, persistent messages using confirm channels
2. Respond with 500 or 503 when a message is returned, ignore the following confirm
3. Return a 200 or 202 (accepted) on a confirm
4. Return a 500 or 501 if the confirm does not arrive within a reasonable period of time
5. If the publish operation yields `false` Respond to new requests with a 503 until a drain event occurs

I created an example web app [here](https://github.com/cressie176/amqplib-express-example) and you might also be interested to read about an amqplib wrapper I wrote called [Rascal](https://github.com/onebeyond/rascal) which tries to make these things a bit easier.

**Closed** 2023-02-25 14:34 UTC
